/**
 * Première bibliothèque exécutable de clauses.
 * Toutes les clauses restent au statut DRAFT_LEGAL_REVIEW_REQUIRED.
 * Elles démontrent l'assemblage déterministe mais ne sont ni APPROVED ni ACTIVE.
 */
export const CLAUSE_CATALOG_VERSION = "0.1.0";

export const CLAUSES = [
  {
    clause_id: "UMOA_FCP_DRAFT_DISCLAIMER_V1",
    version: 1,
    category: "LOCKED_REGULATORY",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "COVER",
    requirements: ["CIRC005_GENERAL_MINIMUM", "CIRC005_GENERAL_ORDER"],
    field_paths: ["regulatory_context.document_status"],
    wording:
      "DOCUMENT DE TRAVAIL — Version générée automatiquement, prête pour revue conformité et juridique. Elle ne constitue ni un agrément, ni un visa, ni une approbation de l’AMF-UMOA.",
  },
  {
    clause_id: "UMOA_FCP_GENERAL_IDENTIFICATION_V1",
    version: 1,
    category: "VALIDATED_PARAMETERIZED",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_1_FCP_DENOMINATION",
    requirements: ["CIRC005_1_1_FCP_DENOMINATION", "CIRC005_1_2_FCP_CONSTITUTION_DATE"],
    field_paths: [
      "fund.legal_name",
      "fund.legal_form",
      "fund.country_of_constitution_name",
      "fund.approval.date_display",
      "fund.approval.number",
    ],
    condition: { path: "fund.legal_form", operator: "equals", value: "FCP" },
    wording:
      "Le Fonds est un {{fund.legal_form}} dénommé « {{fund.legal_name}} », constitué en {{fund.country_of_constitution_name}}. Son agrément a été délivré le {{fund.approval.date_display}} sous le numéro {{fund.approval.number}}.",
  },
  {
    clause_id: "UMOA_FCP_INDEFINITE_DURATION_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_2_FCP_CONSTITUTION_DURATION",
    requirements: ["CIRC005_1_2_FCP_LIMITED_DURATION"],
    field_paths: ["fund.duration_type"],
    condition: { path: "fund.duration_type", operator: "equals", value: "INDEFINITE" },
    wording: "Le Fonds est constitué pour une durée indéterminée.",
  },
  {
    clause_id: "UMOA_FCP_DOCUMENT_AVAILABILITY_V1",
    version: 1,
    category: "VALIDATED_PARAMETERIZED",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_4_DOCUMENT_AVAILABILITY",
    requirements: [
      "CIRC005_1_4_FCP_REGULATION_AVAILABILITY",
      "CIRC005_1_4_FCP_PERIODIC_REPORTS_AVAILABILITY",
    ],
    field_paths: ["documents.availability_summary"],
    wording: "Les documents du Fonds et les rapports périodiques sont disponibles selon les modalités suivantes : {{documents.availability_summary}}.",
  },
  {
    clause_id: "UMOA_FCP_ACCOUNTING_PERIOD_V1",
    version: 1,
    category: "FACTUAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_6_CLOSING_DISTRIBUTIONS",
    requirements: ["CIRC005_1_6_FCP_ACCOUNT_CLOSING_DATE"],
    field_paths: ["accounting.financial_year_end_display"],
    wording: "L’exercice comptable est clôturé le {{accounting.financial_year_end_display}} de chaque année.",
  },
  {
    clause_id: "UMOA_FCP_SINGLE_SHARE_CLASS_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_10_PARTS_CHARACTERISTICS",
    requirements: ["CIRC005_1_10_FCP_PARTS_CHARACTERISTICS"],
    field_paths: ["share_classes"],
    condition: { path: "share_classes.length", operator: "equals", value: 1 },
    wording: "Le Fonds comporte une seule catégorie de parts.",
  },
  {
    clause_id: "UMOA_FCP_NO_VOTING_RIGHTS_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_10_PARTS_CHARACTERISTICS",
    requirements: ["CIRC005_1_10_D_FCP_VOTING_RIGHTS"],
    field_paths: ["parts.voting_rights_exist"],
    condition: { path: "parts.voting_rights_exist", operator: "equals", value: false },
    wording: "Aucun droit de vote n’est attaché aux parts du Fonds.",
  },
  {
    clause_id: "UMOA_FCP_NOT_LISTED_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_11_LISTING",
    requirements: ["CIRC005_1_11_FCP_LISTING_TRADING"],
    field_paths: ["parts.listed", "parts.traded"],
    condition: {
      all: [
        { path: "parts.listed", operator: "equals", value: false },
        { path: "parts.traded", operator: "equals", value: false },
      ],
    },
    wording: "Les parts du Fonds ne sont ni cotées ni admises à la négociation sur un marché.",
  },
  {
    clause_id: "UMOA_FCP_CAPITALIZATION_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_14_INCOME",
    requirements: [
      "CIRC005_1_14_FCP_INCOME_DETERMINATION",
      "CIRC005_1_14_FCP_INCOME_ALLOCATION",
      "CIRC005_1_6_FCP_DISTRIBUTION_DATES",
    ],
    field_paths: ["income.policy"],
    condition: { path: "income.policy", operator: "equals", value: "CAPITALIZATION" },
    wording: "Les revenus du Fonds sont intégralement capitalisés.",
  },
  {
    clause_id: "UMOA_FCP_ACTIVE_MANAGEMENT_V1",
    version: 1,
    category: "COMPOSED",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_15_INVESTMENT_POLICY",
    requirements: [
      "CIRC005_1_15_A_FCP_FINANCIAL_OBJECTIVES",
      "CIRC005_1_15_B_FCP_PLACEMENT_POLICY",
    ],
    field_paths: ["investment.objective.summary", "investment.management_style"],
    condition: { path: "investment.management_style", operator: "equals", value: "ACTIVE_DISCRETIONARY" },
    wording:
      "L’objectif de gestion est le suivant : {{investment.objective.summary}}. La gestion est active et discrétionnaire.",
  },
  {
    clause_id: "UMOA_FCP_BENCHMARK_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_15_INVESTMENT_POLICY",
    requirements: ["CIRC005_1_15_A_FCP_FINANCIAL_OBJECTIVES"],
    field_paths: ["investment.benchmark.name", "investment.benchmark.usage_description"],
    condition: { path: "investment.benchmark.enabled", operator: "equals", value: true },
    wording:
      "L’indicateur de référence est « {{investment.benchmark.name}} ». Il est utilisé de la manière suivante : {{investment.benchmark.usage_description}}.",
  },
  {
    clause_id: "UMOA_FCP_BORROWING_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_15_INVESTMENT_POLICY",
    requirements: ["CIRC005_1_15_F_FCP_BORROWING_CAPACITY"],
    field_paths: ["borrowing.maximum_percent", "borrowing.purpose"],
    condition: { path: "borrowing.allowed", operator: "equals", value: true },
    wording:
      "Le Fonds peut recourir temporairement à l’emprunt, dans la limite de {{borrowing.maximum_percent}} % de son actif, pour le motif suivant : {{borrowing.purpose}}.",
  },
  {
    clause_id: "UMOA_FCP_REDEMPTION_V1",
    version: 1,
    category: "VALIDATED_PARAMETERIZED",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_13_REDEMPTION_SUSPENSION",
    requirements: ["CIRC005_1_13_FCP_REDEMPTION_REIMBURSEMENT"],
    field_paths: [
      "redemption.cutoff.display",
      "redemption.settlement_days.standard_business_days",
      "redemption.execution_nav.description",
    ],
    condition: { path: "redemption.allowed", operator: "equals", value: true },
    wording:
      "Les demandes de rachat sont centralisées au plus tard {{redemption.cutoff.display}} et exécutées sur la base suivante : {{redemption.execution_nav.description}}. Le règlement intervient normalement dans un délai de {{redemption.settlement_days.standard_business_days}} jours ouvrés.",
  },
  {
    clause_id: "UMOA_FCP_REDEMPTION_SUSPENSION_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_13_REDEMPTION_SUSPENSION",
    requirements: ["CIRC005_1_13_FCP_SUSPENSION"],
    field_paths: ["redemption.suspension.circumstances", "redemption.suspension.notification"],
    condition: { path: "redemption.suspension.allowed", operator: "equals", value: true },
    wording:
      "Les rachats peuvent être temporairement suspendus dans les circonstances suivantes : {{redemption.suspension.circumstances}}. L’information est diffusée selon les modalités suivantes : {{redemption.suspension.notification}}.",
  },
  {
    clause_id: "UMOA_FCP_REDEMPTION_GATE_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_13_REDEMPTION_SUSPENSION",
    requirements: ["CIRC005_1_13_FCP_REDEMPTION_REIMBURSEMENT", "CIRC005_1_13_FCP_SUSPENSION"],
    field_paths: ["redemption.gates.threshold_percent", "redemption.gates.execution_method"],
    condition: { path: "redemption.gates.enabled", operator: "equals", value: true },
    wording:
      "Un mécanisme de plafonnement des rachats peut être activé lorsque les demandes représentent plus de {{redemption.gates.threshold_percent}} % de l’actif net. Son exécution suit la méthode suivante : {{redemption.gates.execution_method}}.",
  },
  {
    clause_id: "UMOA_FCP_MANAGER_IDENTITY_V1",
    version: 1,
    category: "FACTUAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_1_SGO_IDENTITY",
    requirements: [
      "CIRC005_1_1_SGO_IDENTITY",
      "CIRC005_1_2_SGO_CONSTITUTION_DATE",
      "CIRC005_1_9_A_SGO_SUBSCRIBED_CAPITAL",
      "CIRC005_1_9_B_SGO_PAID_UP_CAPITAL",
    ],
    field_paths: ["manager.legal_name", "manager.registered_office", "manager.approval.number"],
    wording:
      "La gestion du Fonds est assurée par {{manager.legal_name}}, dont le siège est situé {{manager.registered_office}} et dont l’agrément est référencé {{manager.approval.number}}.",
  },
  {
    clause_id: "UMOA_FCP_DEPOSITARY_IDENTITY_V1",
    version: 1,
    category: "FACTUAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_2_DEPOSITARY",
    requirements: ["CIRC005_2_1_DEPOSITARY_IDENTITY", "CIRC005_2_2_DEPOSITARY_MAIN_ACTIVITY"],
    field_paths: ["depositary.legal_name", "depositary.main_activity"],
    wording:
      "Le dépositaire est {{depositary.legal_name}}. Son activité principale déclarée est : {{depositary.main_activity}}.",
  },
  {
    clause_id: "UMOA_FCP_NO_EXTERNAL_ADVISER_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_3_EXTERNAL_ADVISERS",
    requirements: [
      "CIRC005_3_1_EXTERNAL_ADVISER_IDENTITY",
      "CIRC005_3_2_EXTERNAL_ADVISER_CONTRACT_CLAUSES",
      "CIRC005_3_3_EXTERNAL_ADVISER_OTHER_ACTIVITIES",
    ],
    field_paths: ["external_adviser.enabled"],
    condition: { path: "external_adviser.enabled", operator: "equals", value: false },
    wording: "Aucun conseiller externe rémunéré sur les actifs du Fonds n’est déclaré dans le présent projet.",
  },
  {
    clause_id: "UMOA_FCP_NO_HISTORICAL_PERFORMANCE_V1",
    version: 1,
    category: "CONDITIONAL",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_5_1_HISTORICAL_PERFORMANCE",
    requirements: ["CIRC005_5_1_HISTORICAL_PERFORMANCE"],
    field_paths: ["performance.history_available"],
    condition: { path: "performance.history_available", operator: "equals", value: false },
    wording: "Aucun historique de performance n’est présenté dans cette version du projet.",
  },
  {
    clause_id: "UMOA_FCP_TARGET_INVESTOR_V1",
    version: 1,
    category: "COMPOSED",
    status: "DRAFT_LEGAL_REVIEW_REQUIRED",
    section_id: "SEC_5_2_TARGET_INVESTOR",
    requirements: ["CIRC005_5_2_TARGET_INVESTOR"],
    field_paths: ["target_investor.summary", "target_investor.investment_horizon.display"],
    wording:
      "Le Fonds est destiné au profil suivant : {{target_investor.summary}}. La durée de placement recommandée est de {{target_investor.investment_horizon.display}}.",
  },
];
