import { FUND_CATEGORIES, MEMBER_STATES } from "./constants";
import type { ProspectusQuestion, QuestionGroup } from "./types";

const booleanOptions = [
  { value: "true", label: "Oui" },
  { value: "false", label: "Non" },
];

export const APPLICATION_GROUPS: QuestionGroup[] = [
  {
    id: "risks",
    sequence: 8,
    title: "Risques",
    description: "Questions applicatives conservées avant l’atomisation complète de l’Instruction 66.",
    sourceKind: "PENDING_REGULATORY_MAPPING",
  },
  {
    id: "review",
    sequence: 18,
    title: "Contrôles et revue",
    description: "Pilotage interne de la prochaine revue humaine.",
    sourceKind: "APPLICATION",
  },
];

export const APPLICATION_QUESTIONS: ProspectusQuestion[] = [
  applicationQuestion({
    id: "APP_PROJECT_OPERATION",
    groupId: "project",
    sequence: -30,
    label: "Quel type de projet créez-vous ?",
    helpText: "Métadonnée applicative : création d’un nouveau prospectus ou mise à jour d’un prospectus existant.",
    type: "SELECT",
    required: true,
    fieldPath: "project.operation",
    options: [
      { value: "CREATE", label: "Création d’un nouveau fonds" },
      { value: "UPDATE", label: "Mise à jour d’un prospectus existant" },
    ],
  }),
  applicationQuestion({
    id: "APP_FUND_CATEGORY",
    groupId: "project",
    sequence: -20,
    label: "Quelle est la catégorie principale du fonds ?",
    helpText: "Métadonnée de parcours utilisée pour proposer les questions, risques et méthodes applicables.",
    type: "SELECT",
    required: true,
    fieldPath: "fund.category",
    options: [...FUND_CATEGORIES],
  }),
  applicationQuestion({
    id: "APP_HOME_STATE",
    groupId: "project",
    sequence: -10,
    label: "Dans quel État membre le fonds est-il constitué ?",
    helpText: "Métadonnée applicative utilisée pour initialiser les dispositifs par pays.",
    type: "COUNTRY",
    required: true,
    fieldPath: "fund.countryCode",
    options: [...MEMBER_STATES],
  }),
  applicationQuestion({
    id: "APP_MANAGER_PROFILE_CONFIRMED",
    groupId: "manager",
    sequence: -20,
    label: "Confirmez-vous le profil institutionnel prérempli de la société de gestion ?",
    helpText: "La confirmation utilisateur ne remplace pas la vérification des agréments, statuts et registres officiels.",
    type: "BOOLEAN",
    required: true,
    fieldPath: "managementCompany.confirmed",
    options: booleanOptions,
  }),
  applicationQuestion({
    id: "APP_MANAGER_APPROVAL_NUMBER",
    groupId: "manager",
    sequence: -10,
    label: "Numéro d’agrément de la société de gestion",
    helpText: "Donnée de référentiel à rapprocher du registre officiel AMF-UMOA.",
    type: "TEXT",
    required: true,
    fieldPath: "managementCompany.approvalNumber",
  }),
  applicationQuestion({
    id: "APP_FUND_CURRENCY",
    groupId: "fund",
    sequence: -20,
    label: "Devise comptable du fonds",
    helpText: "Métadonnée canonique utilisée par les parts, les prix et les frais.",
    type: "SELECT",
    required: true,
    fieldPath: "fund.currency",
    options: [
      { value: "XOF", label: "Franc CFA BCEAO (XOF)" },
      { value: "EUR", label: "Euro (EUR)" },
      { value: "USD", label: "Dollar américain (USD)" },
    ],
  }),
  applicationQuestion({
    id: "APP_INITIAL_NAV",
    groupId: "shares",
    sequence: -10,
    label: "Valeur liquidative initiale de la première classe",
    helpText: "Champ applicatif conservé jusqu’à la création du composant structuré d’émission et de prix initial.",
    type: "AMOUNT",
    required: true,
    fieldPath: "shareClasses.0.initialNav",
  }),
  applicationQuestion({
    id: "APP_BENCHMARK_ENABLED",
    groupId: "objective",
    sequence: -20,
    label: "Le fonds utilise-t-il un indicateur de référence ?",
    helpText: "Question applicative de composition. La qualification juridique de l’indicateur reste soumise à revue.",
    type: "BOOLEAN",
    required: true,
    fieldPath: "investment.benchmark.enabled",
    options: booleanOptions,
  }),
  applicationQuestion({
    id: "APP_BENCHMARK_REFERENCE",
    groupId: "objective",
    sequence: -10,
    label: "Nom, administrateur et source de l’indicateur de référence",
    helpText: "Précisez également si l’indicateur est comparatif, contraignant ou répliqué.",
    type: "TEXTAREA",
    required: true,
    fieldPath: "investment.benchmark.reference",
    displayCondition: {
      questionId: "APP_BENCHMARK_ENABLED",
      operator: "EQUALS",
      value: "true",
    },
  }),
  pendingInstruction66Question({
    id: "APP_RISK_CONFIRMATION",
    groupId: "risks",
    sequence: 1,
    label: "Confirmez-vous les risques proposés par le moteur ?",
    helpText: "Question provisoire. La taxonomie et les règles de risques devront provenir du pack Instruction 66 atomisé.",
    type: "BOOLEAN",
    required: true,
    fieldPath: "risks.confirmed",
    options: booleanOptions,
  }),
  pendingInstruction66Question({
    id: "APP_RISK_SPECIFIC",
    groupId: "risks",
    sequence: 2,
    label: "Risque spécifique à ajouter",
    helpText: "Texte libre limité aux risques propres à la stratégie et soumis à revue risques/conformité.",
    type: "TEXTAREA",
    required: false,
    fieldPath: "risks.specific",
  }),
  pendingInstruction66Question({
    id: "APP_REDEMPTION_GATE_ENABLED",
    groupId: "subscriptions",
    sequence: 900,
    label: "Un mécanisme de plafonnement des rachats est-il prévu ?",
    helpText: "Le fondement, les seuils et les conditions doivent être reliés à l’Instruction 66 et au règlement du fonds.",
    type: "BOOLEAN",
    required: true,
    fieldPath: "redemption.gate.enabled",
    options: booleanOptions,
  }),
  pendingInstruction66Question({
    id: "APP_REDEMPTION_GATE_THRESHOLD",
    groupId: "subscriptions",
    sequence: 910,
    label: "Seuil du plafonnement des rachats",
    helpText: "Pourcentage provisoire soumis à validation juridique, risques et conformité.",
    type: "PERCENTAGE",
    required: true,
    fieldPath: "redemption.gate.threshold",
    displayCondition: {
      questionId: "APP_REDEMPTION_GATE_ENABLED",
      operator: "EQUALS",
      value: "true",
    },
  }),
  applicationQuestion({
    id: "APP_TAX_REVIEW_CONFIRMED",
    groupId: "tax",
    sequence: 900,
    label: "La revue fiscale a-t-elle été réalisée par un rôle habilité ?",
    helpText: "Cette confirmation humaine est distincte des réponses fiscales et reste traçable.",
    type: "BOOLEAN",
    required: true,
    fieldPath: "tax.reviewed",
    options: booleanOptions,
    reviewRoles: ["TAX", "LEGAL", "COMPLIANCE"],
  }),
  applicationQuestion({
    id: "APP_EVIDENCE_APPROVALS",
    groupId: "evidence",
    sequence: 900,
    label: "Références des agréments et décisions disponibles",
    helpText: "Prototype local : renseignez une référence ou un chemin. Le stockage documentaire sécurisé reste à implémenter.",
    type: "FILE",
    required: true,
    fieldPath: "evidence.approvals",
  }),
  applicationQuestion({
    id: "APP_REVIEW_OWNER",
    groupId: "review",
    sequence: 1,
    label: "Responsable de la prochaine revue",
    helpText: "Rôle interne chargé de traiter les blocages et avertissements restants.",
    type: "SELECT",
    required: true,
    fieldPath: "review.nextOwner",
    options: [
      { value: "COMPLIANCE", label: "Conformité" },
      { value: "LEGAL", label: "Juridique" },
      { value: "TAX", label: "Fiscalité" },
      { value: "RISK", label: "Risques" },
      { value: "PRODUCT", label: "Métier produit" },
    ],
  }),
];

function applicationQuestion(
  input: Omit<ProspectusQuestion, "requirementIds" | "reviewRoles" | "sourceKind" | "interactive"> & {
    reviewRoles?: string[];
  },
): ProspectusQuestion {
  return {
    ...input,
    requirementIds: [],
    reviewRoles: input.reviewRoles ?? ["PRODUCT", "COMPLIANCE"],
    sourceKind: "APPLICATION",
    interactive: true,
    canonicalFieldPaths: [input.fieldPath],
    implementationStatus: "APPLICATION_CONTROL",
  };
}

function pendingInstruction66Question(
  input: Omit<ProspectusQuestion, "requirementIds" | "reviewRoles" | "sourceKind" | "interactive">,
): ProspectusQuestion {
  return {
    ...input,
    requirementIds: [],
    reviewRoles: ["RISK", "LEGAL", "COMPLIANCE"],
    sourceKind: "PENDING_REGULATORY_MAPPING",
    interactive: true,
    canonicalFieldPaths: [input.fieldPath],
    implementationStatus: "INSTRUCTION66_MAPPING_PENDING",
    sourceReference: "Instruction n°66/CREPMF/2021 — atomisation à compléter",
  };
}
